services:
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pass
      - MONGO_INITDB_DATABASE=auth

  mongo-express:
    image: mongo-express
    depends_on:
      - mongodb
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
      - ME_CONFIG_MONGODB_SERVER=mongodb
    ports:
      - '8081:8081'

  node-app:
    container_name: crosshair-docker-test-container
    image: crosshair-docker-test
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
    ports:
      - '3100:3100'
    volumes:
      - '.:/usr/src/code'
      - '/usr/src/code/node_modules'
    depends_on:
      - mongo-express
